export const ROLES = {
  BACK_OFFICE: 'ROLE_BACK_OFFICE',
  BRANCH_MANAGER: 'ROLE_BRANCH_MANAGER',
  CUSTOMER: 'ROLE_CUSTOMER',
  MARKETING: 'ROLE_MARKETING',
  SUPERADMIN: 'ROLE_SUPERADMIN',
} as const;
